### ISSUE TITLE
2025年假日

### ISSUE THREAD

**Issue by SnDream** [0xcccccccccccc/kholidays_cn#1]
chinese-calendar 已经更新2025年假日，kholidays是否也该同步更新了？
谢谢

**Comment by 0xcccccccccccc** [comment]
理论上ci应该会每天运行，稍晚我会排查一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月27日(周三) 下午2:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [0xcccccccccccc/kholidays_cn] 2025年假日 (Issue #1)




 
chinese-calendar 已经更新2025年假日，kholidays是否也该同步更新了？
 谢谢

**Comment by 0xcccccccccccc** [comment]
看起来60天没有活跃的action会被github停掉

**Comment by SnDream** [comment]
好的，麻烦了。
不过我不是使用arch，而是neon，我在上游代码里直接看到这个仓库链接，所以过来问问。

**Comment by 0xcccccccccccc** [comment]
https://invent.kde.org/frameworks/kholidays/-/merge_requests/103 MR已经提交

**Comment by SnDream** [comment]
非常感谢👍
